import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import React from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { generatedCorpusPages, ssotRegistrySite } from "@ssot-registry/site-content-pack";
import { App } from "../src/App";

const markup = renderToStaticMarkup(<App />);
const styles = readFileSync("src/styles.css", "utf8");
const htmlShell = readFileSync("index.html", "utf8");
const nginxConfig = readFileSync("nginx/default.conf", "utf8");

assert.ok(markup.includes("SSOT Registry"));
assert.ok(!markup.includes("Hello, world."));
assert.ok(markup.includes("Govern software truth from decision to release."));
assert.ok(markup.includes("SSOT Registry learning paths"));
assert.ok(markup.includes("Answer real implementation questions"));
assert.ok(markup.includes("Proof surfaces stay visible"));
assert.ok(markup.includes("The SSOT Registry website teaches the registry from the reader"));
assert.ok(!markup.includes("AEO"));
assert.ok(!markup.includes("AiEO"));
assert.ok(!markup.includes("agent fact"));
assert.ok(!markup.includes("page has"));
assert.ok(!markup.includes("generated corpus proof"));
assert.ok(!markup.includes("Related SSOT Registry package surface"));
assert.ok(markup.includes("application/ld+json"));
assert.ok(markup.includes('"SoftwareApplication"'));
assert.ok(markup.includes('href="/content/features/"'));
assert.ok(markup.includes('href="/content/proofs/"'));
assert.ok(markup.includes('href="/content/packages/"'));
assert.ok(markup.includes('href="/content/faq-qa/"'));
assert.ok(!markup.includes('href="#features"'));
assert.ok(!markup.includes('href="#proof"'));
assert.ok(styles.includes('.lander-page__inner > nav[aria-label="Breadcrumb"]'));
assert.ok(styles.includes(".lander-breadcrumbs"));
assert.ok(styles.includes('[data-lander-theme="lander-dark"] .lander-breadcrumbs'));
assert.ok(!htmlShell.includes("<h1>SSOT Registry</h1>"));
assert.ok(htmlShell.includes("app-boot-shell"));
assert.ok(htmlShell.includes("app-boot-sr"));
assert.ok(nginxConfig.includes('Cache-Control "public, max-age=31536000, immutable"'));
assert.ok(nginxConfig.includes('Cache-Control "no-cache, must-revalidate"'));
assert.ok(ssotRegistrySite.pages.length >= 2500);
assert.equal(generatedCorpusPages.length, 3840);
assert.equal(ssotRegistrySite.pages[0]?.slug, "/");
assert.ok(ssotRegistrySite.pages.some((page) => page.slug === "/content/"));
assert.ok(ssotRegistrySite.pages.some((page) => page.slug === "/content/features/"));
assert.ok(ssotRegistrySite.pages.some((page) => page.slug === "/features/developer/adrs/what-is/"));
