# Generated by ssot-conformance origin generation.
# ssot-conformance-metadata: {"claim_id":"clm:origin.adr.0614.compliance.t2","evidence_id":"evd:t2.origin.adr.0614.compliance.pytest","feature_id":"feat:origin.adr.0614.compliance","kind":"adr","source_id":"adr:0614","template_id":"origin-adr-compliance","template_version":"1.0","test_id":"tst:pytest.origin.adr.0614.compliance"}
from __future__ import annotations

import json
from pathlib import Path


def test_adr_0614_origin_compliance() -> None:
    registry = json.loads((Path.cwd() / '.ssot' / 'registry.json').read_text(encoding='utf-8'))
    rows = {row['id']: row for row in registry.get('adrs', [])}
    row = rows.get('adr:0614')
    assert row is not None, 'adr:0614 must exist in downstream registry'
    assert row.get('origin') == 'ssot-origin'
    assert isinstance(row.get('path'), str) and row['path'].startswith('.ssot/')
