from .boundary import freeze_boundary
from .claims import evaluate_claims
from .config import ensure_repo_config, load_repo_config, resolve_feature_create_auto_scaffold, run_repo_automation, validate_repo_config
from .documents import (
    create_document,
    create_document_reservation,
    delete_document,
    get_document,
    add_spec_adr_links,
    list_document_reservations,
    list_documents,
    remove_spec_adr_links,
    repair_document_hashes,
    set_document_status,
    sync_all_documents,
    sync_documents,
    supersede_documents,
    update_document,
)
from .entity_ops import (
    add_boundary_features,
    add_boundary_profiles,
    add_feature_children,
    add_release_boundaries,
    add_release_claims,
    add_release_evidence,
    create_entity,
    create_feature_with_scaffolded_proof_graph,
    delete_entity,
    get_entity,
    link_entities,
    list_feature_children,
    list_entities,
    remove_boundary_features,
    remove_boundary_profiles,
    remove_feature_children,
    remove_release_boundaries,
    remove_release_claims,
    remove_release_evidence,
    set_claim_status,
    set_claim_tier,
    set_feature_parents,
    set_issue_status,
    set_risk_status,
    unlink_entities,
    update_entity,
)
from .profile_eval import evaluate_feature_passing, evaluate_profile, evaluate_profile_by_id, evaluate_profiles
from .evidence import verify_evidence_rows
from .graph import export_graph
from .init import initialize_repo
from .local_assurance import (
    build_artifact_manifest,
    build_local_evidence_bundle,
    build_source_snapshot,
    deterministic_root_hash,
    verify_local_release,
)
from .lifecycle import set_feature_lifecycle
from .load import load_registry
from .plan import plan_features, plan_issues
from .packs import inspect_pack, preflight_pack, sync_pack
from .origin import sync_origin_assurance_rows
from .proof_graph import certify_feature_proof_graphs
from .registry import export_registry
from .release import certify_release, promote_release, publish_release, revoke_release
from .save import save_registry, save_registry_unchecked
from .status_sync import sync_automated_statuses
from .test_execution import run_boundary_tests, run_resolved_test_rows, run_spec_tests, run_tests
from .upgrade import upgrade_registry
from .validate import validate_registry

__all__ = [
    "initialize_repo",
    "load_registry",
    "save_registry",
    "save_registry_unchecked",
    "validate_registry",
    "ensure_repo_config",
    "load_repo_config",
    "validate_repo_config",
    "resolve_feature_create_auto_scaffold",
    "run_repo_automation",
    "create_document",
    "get_document",
    "list_documents",
    "update_document",
    "add_spec_adr_links",
    "remove_spec_adr_links",
    "repair_document_hashes",
    "set_document_status",
    "supersede_documents",
    "delete_document",
    "sync_documents",
    "sync_all_documents",
    "create_document_reservation",
    "list_document_reservations",
    "create_entity",
    "create_feature_with_scaffolded_proof_graph",
    "get_entity",
    "list_entities",
    "update_entity",
    "delete_entity",
    "link_entities",
    "unlink_entities",
    "set_claim_status",
    "set_claim_tier",
    "set_issue_status",
    "set_risk_status",
    "add_boundary_features",
    "add_boundary_profiles",
    "remove_boundary_features",
    "remove_boundary_profiles",
    "set_feature_parents",
    "add_feature_children",
    "remove_feature_children",
    "list_feature_children",
    "add_release_boundaries",
    "remove_release_boundaries",
    "add_release_claims",
    "remove_release_claims",
    "add_release_evidence",
    "remove_release_evidence",
    "plan_features",
    "plan_issues",
    "inspect_pack",
    "preflight_pack",
    "sync_pack",
    "sync_origin_assurance_rows",
    "certify_feature_proof_graphs",
    "set_feature_lifecycle",
    "build_artifact_manifest",
    "build_local_evidence_bundle",
    "build_source_snapshot",
    "deterministic_root_hash",
    "verify_local_release",
    "evaluate_claims",
    "evaluate_feature_passing",
    "evaluate_profile",
    "evaluate_profile_by_id",
    "evaluate_profiles",
    "verify_evidence_rows",
    "freeze_boundary",
    "certify_release",
    "promote_release",
    "publish_release",
    "revoke_release",
    "export_graph",
    "export_registry",
    "sync_automated_statuses",
    "run_tests",
    "run_spec_tests",
    "run_boundary_tests",
    "run_resolved_test_rows",
    "upgrade_registry",
]
