from __future__ import annotations

CONTRACT_DATA = {
    "schema_version": "0.1.0",
    "output_formats": ["json", "csv", "df", "yaml", "toml"],
    "entity_sections": [
        {"key": "features", "label": "Features"},
        {"key": "profiles", "label": "Profiles"},
        {"key": "tests", "label": "Tests"},
        {"key": "claims", "label": "Claims"},
        {"key": "evidence", "label": "Evidence"},
        {"key": "issues", "label": "Issues"},
        {"key": "risks", "label": "Risks"},
        {"key": "boundaries", "label": "Boundaries"},
        {"key": "releases", "label": "Releases"},
        {"key": "adrs", "label": "ADRs"},
        {"key": "specs", "label": "Specs"},
    ],
    "entity_prefixes": {
        "repo": "repo:",
        "features": "feat:",
        "profiles": "prf:",
        "tests": "tst:",
        "claims": "clm:",
        "evidence": "evd:",
        "issues": "iss:",
        "risks": "rsk:",
        "boundaries": "bnd:",
        "releases": "rel:",
        "adrs": "adr:",
        "specs": "spc:",
    },
    "graph_node_kind": {
        "features": "feature",
        "profiles": "profile",
        "tests": "test",
        "claims": "claim",
        "evidence": "evidence",
        "issues": "issue",
        "risks": "risk",
        "boundaries": "boundary",
        "releases": "release",
    },
    "choice_sets": {
        "feature_implementation_statuses": ["absent", "partial", "implemented"],
        "feature_lifecycle_stages": ["active", "deprecated", "obsolete", "removed"],
        "planning_horizons": ["current", "next", "future", "explicit", "backlog", "out_of_bounds"],
        "test_statuses": ["planned", "passing", "failing", "blocked", "skipped"],
        "profile_statuses": ["draft", "active", "retired"],
        "profile_kinds": ["capability", "certification", "deployment", "interoperability"],
        "claim_tiers": ["T0", "T1", "T2", "T3", "T4"],
        "claim_statuses": [
            "proposed",
            "declared",
            "implemented",
            "asserted",
            "evidenced",
            "certified",
            "promoted",
            "published",
            "blocked",
            "retired",
        ],
        "evidence_statuses": ["planned", "collected", "passed", "failed", "stale"],
        "issue_statuses": ["open", "in_progress", "blocked", "resolved", "closed"],
        "risk_statuses": ["active", "mitigated", "accepted", "retired"],
        "boundary_statuses": ["draft", "active", "frozen", "retired"],
        "release_statuses": ["draft", "candidate", "certified", "promoted", "published", "revoked"],
        "severities": ["low", "medium", "high", "critical"],
        "document_statuses": ["draft", "in_review", "accepted", "rejected", "superseded", "withdrawn", "retired"],
        "spec_kinds": ["normative", "operational", "governance", "local-policy"],
    },
    "document_contract": {
        "kinds": ["adr", "spec"],
        "sections": {"adr": "adrs", "spec": "specs"},
        "filename_prefixes": {"adr": "ADR", "spec": "SPEC"},
        "path_keys": {"adr": "adr_root", "spec": "spec_root"},
        "reservation_keys": {"adr": "adr", "spec": "spec"},
        "default_reservations": {
            "adr": [
                {"owner": "ssot-core", "start": 1, "end": 599, "immutable": True, "deletable": False, "assignable_by_repo": False},
                {"owner": "ssot-origin", "start": 600, "end": 999, "immutable": True, "deletable": False, "assignable_by_repo": False},
                {"owner": "repo-local", "start": 1000, "end": 4999, "immutable": False, "deletable": True, "assignable_by_repo": True},
            ],
            "spec": [
                {"owner": "ssot-core", "start": 1, "end": 599, "immutable": True, "deletable": False, "assignable_by_repo": False},
                {"owner": "ssot-origin", "start": 600, "end": 999, "immutable": True, "deletable": False, "assignable_by_repo": False},
                {"owner": "repo-local", "start": 1000, "end": 4999, "immutable": False, "deletable": True, "assignable_by_repo": True},
            ],
        },
    },
}
