from __future__ import annotations

import hashlib
import json
import re
from copy import deepcopy
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from ssot_registry.api.load import load_registry
from ssot_registry.api.save import save_registry
from ssot_registry.api.validate import validate_registry_document
from ssot_registry.util.jsonio import stable_json_dumps


TEMPLATE_VERSION = "1.0"
GENERATED_MARKER = "# Generated by ssot-conformance origin generation."
MANIFEST_PATH = ".ssot/evidence/conformance/origin-generation-report.json"


@dataclass(frozen=True)
class OriginTemplate:
    id: str
    kind: str
    title: str
    description: str


TEMPLATES: tuple[OriginTemplate, ...] = (
    OriginTemplate(
        id="origin-adr-compliance",
        kind="adr",
        title="ssot-origin ADR compliance",
        description="Validate that a synchronized ssot-origin ADR remains present and origin-tagged in the downstream registry.",
    ),
    OriginTemplate(
        id="origin-spec-compliance",
        kind="spec",
        title="ssot-origin SPEC compliance",
        description="Validate that a synchronized ssot-origin SPEC remains present and origin-tagged in the downstream registry.",
    ),
)


def list_origin_templates() -> list[dict[str, object]]:
    return [template.__dict__.copy() for template in TEMPLATES]


def _slug(value: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")
    return slug or "untitled"


def _registry_path(path: str | Path) -> Path:
    candidate = Path(path)
    if candidate.is_dir():
        return candidate / ".ssot" / "registry.json"
    return candidate


def _entity_slug(row: dict[str, Any]) -> str:
    value = row.get("slug") or row.get("title") or row["id"]
    return _slug(str(value))


def discover_origin_obligations(path: str | Path, *, kinds: list[str] | None = None) -> list[dict[str, object]]:
    registry_path = _registry_path(path)
    registry = json.loads(registry_path.read_text(encoding="utf-8"))
    selected = set(kinds or ["adr", "spec"])
    obligations: list[dict[str, object]] = []
    if "adr" in selected:
        obligations.extend(_obligation_from_row("adr", row) for row in registry.get("adrs", []) if row.get("origin") == "ssot-origin")
    if "spec" in selected:
        obligations.extend(_obligation_from_row("spec", row) for row in registry.get("specs", []) if row.get("origin") == "ssot-origin")
    return sorted(obligations, key=lambda row: (str(row["kind"]), int(row["number"])))


def _obligation_from_row(kind: str, row: dict[str, Any]) -> dict[str, object]:
    number = int(row["number"])
    slug = _entity_slug(row)
    return {
        "kind": kind,
        "source_id": row["id"],
        "number": number,
        "slug": slug,
        "title": row.get("title", row["id"]),
        "path": row.get("path"),
        "template_id": f"origin-{kind}-compliance",
    }


def _target_ids(obligation: dict[str, object]) -> dict[str, str]:
    kind = str(obligation["kind"])
    number = int(obligation["number"])
    stem = f"origin.{kind}.{number:04d}.compliance"
    return {
        "feature": f"feat:{stem}",
        "claim": f"clm:{stem}.t2",
        "test": f"tst:pytest.{stem}",
        "evidence": f"evd:t2.{stem}.pytest",
    }


def _test_path(obligation: dict[str, object]) -> str:
    kind = str(obligation["kind"])
    number = int(obligation["number"])
    slug = _slug(str(obligation["slug"]))
    return f"tests/conformance/origin/test_{kind}_{number:04d}_{slug}.py"


def _execution(path: str) -> dict[str, object]:
    return {
        "mode": "command",
        "argv": ["python", "-m", "pytest", path, "-q"],
        "cwd": ".",
        "env": {},
        "timeout_seconds": 600,
        "success": {"type": "exit_code", "expected": 0},
    }


def _metadata(obligation: dict[str, object]) -> dict[str, object]:
    ids = _target_ids(obligation)
    return {
        "template_id": obligation["template_id"],
        "template_version": TEMPLATE_VERSION,
        "kind": obligation["kind"],
        "source_id": obligation["source_id"],
        "feature_id": ids["feature"],
        "claim_id": ids["claim"],
        "test_id": ids["test"],
        "evidence_id": ids["evidence"],
    }


def render_origin_test(obligation: dict[str, object]) -> str:
    metadata = _metadata(obligation)
    source_id = str(obligation["source_id"])
    kind = str(obligation["kind"])
    section = "adrs" if kind == "adr" else "specs"
    return (
        f"{GENERATED_MARKER}\n"
        f"# ssot-conformance-metadata: {json.dumps(metadata, sort_keys=True, separators=(',', ':'))}\n"
        "from __future__ import annotations\n\n"
        "import json\n"
        "from pathlib import Path\n\n\n"
        f"def test_{kind}_{int(obligation['number']):04d}_origin_compliance() -> None:\n"
        "    registry = json.loads((Path.cwd() / '.ssot' / 'registry.json').read_text(encoding='utf-8'))\n"
        f"    rows = {{row['id']: row for row in registry.get('{section}', [])}}\n"
        f"    row = rows.get('{source_id}')\n"
        f"    assert row is not None, '{source_id} must exist in downstream registry'\n"
        f"    assert row.get('origin') == 'ssot-origin'\n"
        "    assert isinstance(row.get('path'), str) and row['path'].startswith('.ssot/')\n"
    )


def _row_bundle(obligation: dict[str, object], *, include_claims: bool, include_evidence: bool) -> dict[str, dict[str, object]]:
    ids = _target_ids(obligation)
    test_path = _test_path(obligation)
    kind = str(obligation["kind"])
    number = int(obligation["number"])
    title = str(obligation["title"])
    spec_ids = [str(obligation["source_id"])] if kind == "spec" else []
    feature = {
        "id": ids["feature"],
        "title": f"Origin {kind.upper()} {number:04d} compliance",
        "description": f"Generated downstream conformance coverage for ssot-origin {kind.upper()} {number:04d}: {title}.",
        "implementation_status": "implemented",
        "lifecycle": {"stage": "active", "replacement_feature_ids": [], "note": None},
        "plan": {"horizon": "current", "slot": "ssot-origin-conformance-generation.v1", "target_claim_tier": "T2", "target_lifecycle_stage": "active"},
        "spec_ids": spec_ids,
        "claim_ids": [ids["claim"]] if include_claims else [],
        "test_ids": [ids["test"]],
        "requires": [],
        "parent_feature_ids": [],
        "origin": "repo-local",
    }
    claim = {
        "id": ids["claim"],
        "title": f"Origin {kind.upper()} {number:04d} compliance is generated",
        "status": "certified",
        "tier": "T2",
        "kind": "conformance",
        "description": f"The generated downstream origin conformance test covers {obligation['source_id']}.",
        "feature_ids": [ids["feature"]],
        "test_ids": [ids["test"]],
        "evidence_ids": [ids["evidence"]] if include_evidence else [],
        "depends_on_claim_ids": [],
        "origin": "repo-local",
    }
    test = {
        "id": ids["test"],
        "title": f"Origin {kind.upper()} {number:04d} generated compliance test",
        "status": "passing",
        "kind": "pytest",
        "path": test_path,
        "feature_ids": [ids["feature"]],
        "claim_ids": [ids["claim"]] if include_claims else [],
        "evidence_ids": [ids["evidence"]] if include_evidence else [],
        "execution": _execution(test_path),
        "origin": "repo-local",
    }
    evidence = {
        "id": ids["evidence"],
        "title": f"Origin {kind.upper()} {number:04d} generated compliance evidence",
        "status": "passed",
        "kind": "pytest",
        "tier": "T2",
        "path": MANIFEST_PATH,
        "claim_ids": [ids["claim"]],
        "test_ids": [ids["test"]],
        "robustness_dimensions": ["positive", "integration"],
        "source_evidence_ids": [],
        "origin": "repo-local",
    }
    return {"feature": feature, "claim": claim, "test": test, "evidence": evidence}


def _index(registry: dict[str, Any], section: str) -> dict[str, dict[str, Any]]:
    return {row["id"]: row for row in registry.get(section, []) if isinstance(row, dict) and isinstance(row.get("id"), str)}


def plan_origin_conformance(
    path: str | Path,
    *,
    kinds: list[str] | None = None,
    include_claims: bool = False,
    include_evidence: bool = False,
) -> dict[str, object]:
    registry_path = _registry_path(path)
    repo_root = registry_path.parent.parent
    registry = json.loads(registry_path.read_text(encoding="utf-8"))
    obligations = discover_origin_obligations(path, kinds=kinds)
    existing = {section: _index(registry, section) for section in ("features", "claims", "tests", "evidence")}
    generated_files = []
    missing = {"features": [], "claims": [], "tests": [], "evidence": []}
    for obligation in obligations:
        ids = _target_ids(obligation)
        bundle = _row_bundle(obligation, include_claims=include_claims, include_evidence=include_evidence)
        path_value = _test_path(obligation)
        rendered = render_origin_test(obligation)
        target = repo_root / path_value
        current = target.read_text(encoding="utf-8") if target.exists() else None
        generated_files.append(
            {
                "path": path_value,
                "template_id": obligation["template_id"],
                "source_id": obligation["source_id"],
                "exists": target.exists(),
                "changed": current != rendered,
                "sha256": hashlib.sha256(rendered.encode("utf-8")).hexdigest(),
            }
        )
        if ids["feature"] not in existing["features"]:
            missing["features"].append(ids["feature"])
        if include_claims and ids["claim"] not in existing["claims"]:
            missing["claims"].append(ids["claim"])
        if ids["test"] not in existing["tests"]:
            missing["tests"].append(ids["test"])
        if include_evidence and ids["evidence"] not in existing["evidence"]:
            missing["evidence"].append(ids["evidence"])
        obligation["rows"] = bundle
    return {
        "passed": True,
        "templates": list_origin_templates(),
        "obligations": obligations,
        "generated_files": generated_files,
        "missing": missing,
        "include_claims": include_claims,
        "include_evidence": include_evidence,
    }


def _upsert_row(registry: dict[str, Any], section: str, row: dict[str, object]) -> str:
    lookup = _index(registry, section)
    if row["id"] in lookup:
        if lookup[str(row["id"])] == row:
            return "unchanged"
        lookup[str(row["id"])].clear()
        lookup[str(row["id"])].update(deepcopy(row))
        return "updated"
    registry.setdefault(section, []).append(deepcopy(row))
    return "created"


def _write_report(repo_root: Path, plan: dict[str, object], result: dict[str, object], output_path: str | Path | None) -> str:
    target = repo_root / MANIFEST_PATH if output_path is None else Path(output_path)
    if not target.is_absolute():
        target = repo_root / target
    target.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "passed": result["passed"],
        "template_version": TEMPLATE_VERSION,
        "obligation_count": len(plan["obligations"]),
        "generated_files": plan["generated_files"],
        "created": result["created"],
        "updated": result["updated"],
        "unchanged": result["unchanged"],
    }
    target.write_text(stable_json_dumps(payload), encoding="utf-8")
    return target.relative_to(repo_root).as_posix()


def apply_origin_conformance(
    path: str | Path,
    *,
    kinds: list[str] | None = None,
    include_claims: bool = False,
    include_evidence: bool = False,
    dry_run: bool = False,
    overwrite: bool = False,
    report_output: str | Path | None = None,
) -> dict[str, object]:
    plan = plan_origin_conformance(path, kinds=kinds, include_claims=include_claims, include_evidence=include_evidence)
    if dry_run:
        return {**plan, "dry_run": True}

    registry_path, repo_root, registry = load_registry(path)
    created = {"features": [], "claims": [], "tests": [], "evidence": [], "files": []}
    updated = {"features": [], "claims": [], "tests": [], "evidence": [], "files": []}
    unchanged = {"features": [], "claims": [], "tests": [], "evidence": [], "files": []}

    for obligation in plan["obligations"]:
        rendered = render_origin_test(obligation)
        target_rel = _test_path(obligation)
        target = repo_root / target_rel
        if target.exists():
            current = target.read_text(encoding="utf-8")
            if current == rendered:
                unchanged["files"].append(target_rel)
            elif not current.startswith(GENERATED_MARKER) and not overwrite:
                raise ValueError(f"Refusing to overwrite locally edited origin conformance test: {target_rel}")
            else:
                target.write_text(rendered, encoding="utf-8")
                updated["files"].append(target_rel)
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(rendered, encoding="utf-8")
            created["files"].append(target_rel)

        rows = _row_bundle(obligation, include_claims=include_claims, include_evidence=include_evidence)
        for section, row_key in (("features", "feature"), ("claims", "claim"), ("tests", "test"), ("evidence", "evidence")):
            if section == "claims" and not include_claims:
                continue
            if section == "evidence" and not include_evidence:
                continue
            action = _upsert_row(registry, section, rows[row_key])
            {"created": created, "updated": updated, "unchanged": unchanged}[action][section].append(str(rows[row_key]["id"]))

    preliminary: dict[str, object] = {
        "passed": True,
        "created": created,
        "updated": updated,
        "unchanged": unchanged,
    }
    report_path = None
    if include_evidence:
        report_path = _write_report(repo_root, plan, preliminary, report_output)

    report = validate_registry_document(registry, registry_path, repo_root)
    if not report["passed"]:
        failures = "; ".join(report["failures"])
        raise ValueError(f"Registry validation failed after origin conformance generation: {failures}")
    save_registry(registry_path, registry)
    result: dict[str, object] = {
        "passed": True,
        "dry_run": False,
        "templates": plan["templates"],
        "obligations": plan["obligations"],
        "generated_files": plan["generated_files"],
        "created": created,
        "updated": updated,
        "unchanged": unchanged,
        "validation": report,
    }
    if report_path is not None:
        result["report_path"] = report_path
    return result
